dist: bionic

language: generic

branches:
  only:
  - master

env: 

sudo: required

git:
  depth: 1

# https://stackoverflow.com/questions/35942754/how-to-save-username-and-password-in-git
before_install:
  - git config --global user.name "worksg"
  - git config --global user.email "571940753@qq.com"
  - git config --global credential.helper store
  - echo "https://worksg:${travis_ci_token}@github.com" > ~/.git-credentials
  - chmod u+x auto-update.sh

install:
  - ./auto-update.sh

before_script:

script: